name: 💡 Предложить функцию
description: Предложите новую функцию или улучшение для проекта
title: "[Функция]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за ваше предложение!
        
        Пожалуйста, убедитесь, что подобная функция ещё не была предложена в других issues.
  - type: checkboxes
    id: searched
    attributes:
      label: Проверка существующих предложений
      description: Я проверил существующие issues и обсуждения
      options:
        - label: Я проверил существующие issues и убедился, что подобное предложение отсутствует
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Описание функции
      description: Опишите предлагаемую функцию или улучшение как можно подробнее
      placeholder: "Я хочу, чтобы скрипт мог..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Мотивация
      description: Почему эта функция будет полезна? Какую проблему она решает?
      placeholder: "Эта функция решит проблему..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение (опционально)
      description: Если у вас есть идеи о том, как это можно реализовать, опишите их
      placeholder: "Можно реализовать через..."
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Готовность помочь
      description: Можете ли вы помочь с реализацией этой функции?
      options:
        - label: Я готов помочь с реализацией этой функции
          required: false
